# CMake generated Testfile for 
# Source directory: /Users/lixiang/wx-files/minidb/tests
# Build directory: /Users/lixiang/wx-files/minidb/build-asan/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[lock_manager_wait_test]=] "/Users/lixiang/wx-files/minidb/build-asan/tests/lock_manager_wait_test")
set_tests_properties([=[lock_manager_wait_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;42;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[tuple_value_edge_test]=] "/Users/lixiang/wx-files/minidb/build-asan/tests/tuple_value_edge_test")
set_tests_properties([=[tuple_value_edge_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;43;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[page_store_remote_test]=] "/Users/lixiang/wx-files/minidb/build-asan/tests/page_store_remote_test")
set_tests_properties([=[page_store_remote_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;44;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[wal_buffer_pool_test]=] "/Users/lixiang/wx-files/minidb/build-asan/tests/wal_buffer_pool_test")
set_tests_properties([=[wal_buffer_pool_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;45;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[transaction_slots_test]=] "/Users/lixiang/wx-files/minidb/build-asan/tests/transaction_slots_test")
set_tests_properties([=[transaction_slots_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;46;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[btree_property_test]=] "/Users/lixiang/wx-files/minidb/build-asan/tests/btree_property_test" "12648434")
set_tests_properties([=[btree_property_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;47;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[index_key_btree_test]=] "/Users/lixiang/wx-files/minidb/build-asan/tests/index_key_btree_test")
set_tests_properties([=[index_key_btree_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;48;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[datetime_parse_test]=] "/Users/lixiang/wx-files/minidb/build-asan/tests/datetime_parse_test")
set_tests_properties([=[datetime_parse_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;49;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[sql_regression]=] "bash" "/Users/lixiang/wx-files/minidb/tests/sql/sql_regression.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[sql_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;55;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[sql_keyword_combinations]=] "bash" "/Users/lixiang/wx-files/minidb/tests/sql/sql_keyword_combinations.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[sql_keyword_combinations]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;57;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[full_sql_suite]=] "bash" "/Users/lixiang/wx-files/minidb/tests/sql/full_sql_suite.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[full_sql_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;59;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[datetime_types]=] "bash" "/Users/lixiang/wx-files/minidb/tests/sql/datetime_types.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[datetime_types]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;61;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[join_syntax_strict]=] "bash" "/Users/lixiang/wx-files/minidb/tests/sql/join_syntax_strict.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[join_syntax_strict]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;63;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[semantic_validation]=] "bash" "/Users/lixiang/wx-files/minidb/tests/sql/semantic_validation.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[semantic_validation]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;65;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[join_optimizer]=] "bash" "/Users/lixiang/wx-files/minidb/tests/sql/join_optimizer.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[join_optimizer]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;67;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[filter_pushdown]=] "bash" "/Users/lixiang/wx-files/minidb/tests/sql/filter_pushdown.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[filter_pushdown]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;69;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[sql_correctness_matrix]=] "python3" "/Users/lixiang/wx-files/minidb/tests/sql/sql_correctness_matrix.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648430")
set_tests_properties([=[sql_correctness_matrix]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;71;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[differential_sqlite]=] "python3" "/Users/lixiang/wx-files/minidb/tests/sql/differential_sqlite.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648431")
set_tests_properties([=[differential_sqlite]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;73;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[select_empty_list]=] "python3" "/Users/lixiang/wx-files/minidb/tests/sql/select_empty_list.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648444")
set_tests_properties([=[select_empty_list]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;75;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[p1_features]=] "python3" "/Users/lixiang/wx-files/minidb/tests/sql/p1_features_test.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648455")
set_tests_properties([=[p1_features]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;77;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[alter_table_semantics]=] "bash" "/Users/lixiang/wx-files/minidb/tests/ddl/alter_table_semantics.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[alter_table_semantics]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;84;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[hot_index_semantics]=] "bash" "/Users/lixiang/wx-files/minidb/tests/ddl/hot_index_semantics.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[hot_index_semantics]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;86;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[persistence_and_composite]=] "bash" "/Users/lixiang/wx-files/minidb/tests/index/persistence_and_composite.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[persistence_and_composite]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;93;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[index_delete_rebuild]=] "bash" "/Users/lixiang/wx-files/minidb/tests/index/index_delete_rebuild.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[index_delete_rebuild]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;95;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[index_unique_matrix]=] "bash" "/Users/lixiang/wx-files/minidb/tests/index/index_unique_matrix.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[index_unique_matrix]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;97;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[mvcc_lock_regression]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/isolation/mvcc_lock_regression.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648433")
set_tests_properties([=[mvcc_lock_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;104;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[lost_update]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/isolation/lost_update.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648438")
set_tests_properties([=[lost_update]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;106;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[mvcc_visibility_matrix]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/isolation/mvcc_visibility_matrix.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648446")
set_tests_properties([=[mvcc_visibility_matrix]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;108;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[write_skew]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/isolation/write_skew.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648439")
set_tests_properties([=[write_skew]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;110;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[write_skew_serializable]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/isolation/write_skew_serializable.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648460")
set_tests_properties([=[write_skew_serializable]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;112;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[phantom_read]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/isolation/phantom_read.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648456")
set_tests_properties([=[phantom_read]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;114;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[long_snapshot_gc]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/isolation/long_snapshot_gc.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648458")
set_tests_properties([=[long_snapshot_gc]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;116;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[vacuum_concurrent]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/isolation/vacuum_concurrent.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648459")
set_tests_properties([=[vacuum_concurrent]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;118;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[commit_durability]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/atomicity/commit_durability.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648435")
set_tests_properties([=[commit_durability]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;120;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[index_heap_atomic]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/atomicity/index_heap_atomic.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648441")
set_tests_properties([=[index_heap_atomic]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;122;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[clog_status_log]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/atomicity/clog_status_log.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648450")
set_tests_properties([=[clog_status_log]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;124;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[statement_savepoint]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/atomicity/statement_savepoint.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648451")
set_tests_properties([=[statement_savepoint]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;126;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[ddl_implicit_commit]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/atomicity/ddl_implicit_commit.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648453")
set_tests_properties([=[ddl_implicit_commit]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;128;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[constraints_not_null_default]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/consistency/constraints_not_null_default.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648437")
set_tests_properties([=[constraints_not_null_default]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;130;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[post_recovery_verify]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/consistency/post_recovery_verify.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648442")
set_tests_properties([=[post_recovery_verify]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;132;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[varchar_length]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/consistency/varchar_length.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648445")
set_tests_properties([=[varchar_length]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;134;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[check_constraint]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/consistency/check_constraint.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648452")
set_tests_properties([=[check_constraint]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;136;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[null_three_valued_logic]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/consistency/null_three_valued_logic.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648454")
set_tests_properties([=[null_three_valued_logic]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;138;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[recovery_smoke]=] "bash" "/Users/lixiang/wx-files/minidb/tests/acid/durability/recovery_smoke.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[recovery_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;140;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[wal_replay_slot_reuse]=] "bash" "/Users/lixiang/wx-files/minidb/tests/acid/durability/wal_replay_slot_reuse.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[wal_replay_slot_reuse]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;142;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[torn_page]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/durability/torn_page.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648436")
set_tests_properties([=[torn_page]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;144;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[checkpoint_barrier]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/durability/checkpoint_barrier.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648440")
set_tests_properties([=[checkpoint_barrier]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;146;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[wal_record_corruption]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/durability/wal_record_corruption.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648447")
set_tests_properties([=[wal_record_corruption]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;148;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[index_state_machine]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/durability/index_state_machine.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648448")
set_tests_properties([=[index_state_machine]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;150;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[ddl_wal]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/durability/ddl_wal.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648449")
set_tests_properties([=[ddl_wal]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;152;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[crash_recovery_harness]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/durability/crash_recovery_harness.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648432")
set_tests_properties([=[crash_recovery_harness]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;154;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[ddl_crash_recovery]=] "python3" "/Users/lixiang/wx-files/minidb/tests/acid/durability/ddl_crash_recovery.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648457")
set_tests_properties([=[ddl_crash_recovery]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;156;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[remote_page_store]=] "bash" "/Users/lixiang/wx-files/minidb/tests/storage/remote_page_store.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[remote_page_store]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;163;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[performance_paths]=] "bash" "/Users/lixiang/wx-files/minidb/tests/performance/performance_paths.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[performance_paths]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;170;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[performance_delivery]=] "bash" "/Users/lixiang/wx-files/minidb/tests/performance/performance_delivery.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[performance_delivery]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;172;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[performance_optimizations]=] "bash" "/Users/lixiang/wx-files/minidb/tests/performance/performance_optimizations.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[performance_optimizations]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;174;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[bulk_update_delete_perf]=] "bash" "/Users/lixiang/wx-files/minidb/tests/performance/bulk_update_delete_perf.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[bulk_update_delete_perf]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;176;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[production_regression]=] "bash" "/Users/lixiang/wx-files/minidb/tests/regression/production_regression.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[production_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;183;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[resource_limits]=] "bash" "/Users/lixiang/wx-files/minidb/tests/regression/resource_limits.sh" "/Users/lixiang/wx-files/minidb/build-asan/minidb")
set_tests_properties([=[resource_limits]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;185;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[update_halloween]=] "python3" "/Users/lixiang/wx-files/minidb/tests/regression/update_halloween.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648443")
set_tests_properties([=[update_halloween]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;187;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
add_test([=[lsn_watermark_restart]=] "python3" "/Users/lixiang/wx-files/minidb/tests/regression/lsn_watermark_restart.py" "/Users/lixiang/wx-files/minidb/build-asan/minidb" "--seed" "12648445")
set_tests_properties([=[lsn_watermark_restart]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;189;add_test;/Users/lixiang/wx-files/minidb/tests/CMakeLists.txt;0;")
